### ISSUE TITLE
Method#== is not implemented correctly

### ISSUE THREAD

**Issue by mame** [ksss/mruby-method#2]
Hello,

Comparison between Method objects seems to always return true.  Is this intentional?

```
$ ./bin/mruby -e 'p 0.method(:+) == 0.method(:-)'
true

$ ./bin/mruby -e 'p 0.method(:+).eql?(0.method(:-))'
true
```

Thank you,

**Comment by ksss** [comment]
@mame This is the bug. Thank you for reporting!
