### ISSUE TITLE
Tests don't run on latest mruby anymore

### ISSUE THREAD

**Issue by Asmod4n** [ksss/mruby-method#6]
See https://github.com/mruby/mruby/issues/3708.

Cannot hunt it down, have commented out most tests and it still doesn't run, sometimes it runs when the 2nd test is removed, but then not anymore when other tests are enabled again :/

**Comment by Asmod4n** [comment]
This got a repo with https://github.com/mruby/mruby/issues/3715, this can be closed.

**Comment by ksss** [comment]
Maybe it is mruby-method's issue.

**Comment by ksss** [comment]
@Asmod4n Fixed https://github.com/ksss/mruby-method/commit/eac60f364243d9536e51b001aa6e6d069661d139
